sudo: false

language: php
php:
 - 7.0

before_script:
 - phpenv config-rm xdebug.ini
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.2
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0
 - chmod +x ci.sh

script:
 - ./ci.sh

notifications:
  email: false

deploy:
  provider: releases
  api_key: "77b9468d46c6597e5d76c4cc61e392ab5b420bf0"
  file: "Elywing.phar"
  skip_cleanup: true
  on:
    tags: false
