sudo: false

language: php
php:
 - 7.0

before_script:
 - phpenv config-rm xdebug.ini
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.2
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0
 - chmod +x ci.sh

script:
 - ./ci.sh

notifications:
  email: false

deploy:
  provider: releases
  api_key: "b5e6a5d21bb4100ec5b910029ae0b6b3d5fe5727"
  file: "Elywing.phar"
  skip_cleanup: true
  on:
    tags: true
